### ISSUE TITLE
Broken links to images

### ISSUE THREAD

**Issue by ChinmayMhatre** [BurakTaner/BurakTaner#1]
Was going through the readme. I found some broken links to the technology images.
![image](https://user-images.githubusercontent.com/51131670/210227278-f9d5beeb-5a07-4991-be36-fb298a1f6f7e.png)

**Comment by ErtanTaner** [comment]
Interesting, it's working normally on my side. Do you have any idea? @ChinmayMhatre

**Comment by ChinmayMhatre** [comment]
Maybe the images have been deleted from the url that is put in the readme. Where have you taken the images from?

**Comment by ChinmayMhatre** [comment]
I just look at the repo you generated your github profile from https://github.com/rahuldkjain/github-profile-readme-generator

I saw that the images are missing from them as well. Maybe the links have expired

![image](https://user-images.githubusercontent.com/51131670/210310938-cc4ebc56-6851-4e76-822d-67f96a81d82b.png)

**Comment by ChinmayMhatre** [comment]
What I think should be done is . you could the images for the technologies you want . and host the image in one of the issue on this repo itself .

**Comment by ChinmayMhatre** [comment]
What I think you could do is . you could download the images for the technologies you want and host the image in one of the issue on this repo itself . Then replace the broken links with those

**Comment by ErtanTaner** [comment]
Yeah, thats a good idea. Thanks Chinmany :) @ChinmayMhatre
